etheriq_lesson6_homepage:
    pattern:  /
    defaults: { _controller: EtheriqLesson6Bundle:Default:index }

etheriq_lesson6_insert_printer:
    pattern:  /ins
    defaults: { _controller: EtheriqLesson6Bundle:Printer:insert }
